openapi: 3.2.0
info:
  title: LibreTranslate Translate API
  version: 1.9.6
  description: Free and Open Source Machine Translation API.
  license:
    name: AGPL-3.0
servers:
- url: /
tags:
- name: Translate
paths:
  /languages:
    get:
      summary: Get Supported Languages
      tags:
      - Translate
      responses:
        '200':
          description: List of supported languages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/languages'
      operationId: getLanguages
      x-operation-id-source: derived
  /detect:
    post:
      summary: Detect Language of Text
      tags:
      - Translate
      responses:
        '200':
          description: Detections
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/detections'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '403':
          description: Banned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '429':
          description: Slow down
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-slow-down'
        '500':
          description: Detection error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                q:
                  description: Text to detect
                api_key:
                  description: API key
              required:
              - q
      operationId: postDetect
      x-operation-id-source: derived
  /translate:
    post:
      summary: Translate Text
      tags:
      - Translate
      responses:
        '200':
          description: Translation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/translate'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '403':
          description: Banned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '429':
          description: Slow down
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-slow-down'
        '500':
          description: Translation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                q:
                  description: Text(s) to translate
                source:
                  description: Source language code or "auto" for auto detection
                target:
                  description: Target language code
                format:
                  description: "Format of source text:\n * `text` - Plain text\n * `html` - HTML markup\n"
                alternatives:
                  description: Preferred number of alternative translations
                api_key:
                  description: API key
              required:
              - q
              - source
              - target
      operationId: postTranslate
      x-operation-id-source: derived
  /translate_file:
    post:
      summary: Translate a File
      tags:
      - Translate
      responses:
        '200':
          description: Translated file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/translate-file'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '403':
          description: Banned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
        '429':
          description: Slow down
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-slow-down'
        '500':
          description: Translation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-response'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: File to translate
                  format: binary
                source:
                  description: Source language code or "auto" for auto detection
                target:
                  description: Target language code
                api_key:
                  description: API key
              required:
              - file
              - source
              - target
      operationId: postTranslateFile
      x-operation-id-source: derived
components:
  schemas:
    translate-file:
      type: object
      properties:
        translatedFileUrl:
          type: string
          description: Translated file url
    languages:
      type: array
      items:
        type: object
        description: Supported language
        properties:
          code:
            type: string
            description: Language code
          name:
            type: string
            description: Human-readable language name (in English)
          targets:
            type: array
            description: Supported target language codes
            items:
              type: string
    detections:
      type: array
      items:
        type: object
        properties:
          language:
            type: string
            description: Language code
            example: en
          confidence:
            type: number
            format: float
            description: Confidence value
            minimum: 0
            maximum: 100
            example: 100
    error-response:
      type: object
      properties:
        error:
          type: string
          description: Error message
    translate:
      type: object
      required:
      - translatedText
      properties:
        translatedText:
          oneOf:
          - type: string
          - type: array
          description: Translated text(s)
        detectedLanguage:
          oneOf:
          - type: object
            properties:
              language:
                type: string
                description: Language code
              confidence:
                type: number
                format: float
                description: Confidence value
                minimum: 0
                maximum: 100
                example: 100
          - type: array
            items:
              type: object
              properties:
                language:
                  type: string
                  description: Language code
                confidence:
                  type: number
                  format: float
                  description: Confidence value
                  minimum: 0
                  maximum: 100
                  example: 100
        alternatives:
          oneOf:
          - type: array
            items:
              type: string
          - type: array
            items:
              type: array
              items:
                type: string
          description: Alternative translations
    error-slow-down:
      type: object
      properties:
        error:
          type: string
          description: Reason for slow down
